/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by: scripts/generate-skeleton-types.js
 * Source: projects/osi-cards-lib/src/lib/components/sections/
 * Run: npm run generate:skeleton-types
 * Generated at: 2025-12-01T18:22:21.150Z
 */

/**
 * All section types discovered from the sections directory.
 * This is the single source of truth for available section types.
 */
export const ALL_SECTION_TYPES = [
  'analytics',
  'brand-colors',
  'chart',
  'code',
  'comparison',
  'contact-card',
  'event',
  'faq',
  'financials',
  'gallery',
  'info',
  'kanban',
  'list',
  'map',
  'network-card',
  'news',
  'overview',
  'pricing',
  'product',
  'quotation',
  'rating',
  'social',
  'social-media',
  'solutions',
  'text-reference',
  'timeline',
  'video',
] as const;

/**
 * Type representing all available section types
 */
export type SectionType = (typeof ALL_SECTION_TYPES)[number];

/**
 * Total number of section types available
 */
export const SECTION_TYPE_COUNT = 27;

/**
 * Check if a string is a valid section type
 */
export function isValidSectionType(type: string): type is SectionType {
  return (ALL_SECTION_TYPES as readonly string[]).includes(type.toLowerCase());
}

/**
 * Get all section types as an array (for runtime use)
 */
export function getAllSectionTypes(): string[] {
  return [...ALL_SECTION_TYPES];
}

/**
 * Metadata about the generated types
 */
export const SKELETON_TYPES_META = {
  generatedAt: '2025-12-01T18:22:21.150Z',
  sourceDirectory: 'projects/osi-cards-lib/src/lib/components/sections/',
  totalTypes: 27,
};
