#!/usr/bin/env node

/**
 * Generate version.ts file for runtime version access
 * This script is run during build to ensure version info is available
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const PACKAGE_JSON = path.join(__dirname, '..', 'package.json');
const VERSION_FILE = path.join(__dirname, '..', 'src', 'version.ts');

/**
 * Get git commit hash
 */
function getGitHash() {
  try {
    return execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
  } catch {
    return 'unknown';
  }
}

/**
 * Get git branch name
 */
function getGitBranch() {
  try {
    return execSync('git rev-parse --abbrev-ref HEAD', { encoding: 'utf8' }).trim();
  } catch {
    return 'unknown';
  }
}

/**
 * Generate version.ts file
 */
function generateVersionFile() {
  // Read version from package.json
  let version = '0.0.0';
  try {
    const packageJson = JSON.parse(fs.readFileSync(PACKAGE_JSON, 'utf8'));
    version = packageJson.version || version;
  } catch (error) {
    console.warn('Could not read package.json version:', error.message);
  }

  const buildDate = new Date().toISOString();
  const buildHash = getGitHash();
  const buildBranch = getGitBranch();

  const content = `/**
 * Auto-generated version file
 * Do not edit manually - this file is generated by generate-version.js
 * Updated during build process
 */

export const VERSION = '${version}';
export const BUILD_DATE = '${buildDate}';
export const BUILD_HASH = '${buildHash}';
export const BUILD_BRANCH = '${buildBranch}';

export interface VersionInfo {
  version: string;
  buildDate: string;
  buildHash: string;
  buildBranch: string;
}

export const VERSION_INFO: VersionInfo = {
  version: VERSION,
  buildDate: BUILD_DATE,
  buildHash: BUILD_HASH,
  buildBranch: BUILD_BRANCH
};

/**
 * Get formatted version string
 */
export function getVersionString(): string {
  return \`\${VERSION} (\${BUILD_BRANCH}@\${BUILD_HASH})\`;
}

/**
 * Check if current build is a production build
 */
export function isProductionBuild(): boolean {
  return BUILD_BRANCH === 'main' || BUILD_BRANCH === 'master';
}
`;

  // Ensure src directory exists
  const srcDir = path.dirname(VERSION_FILE);
  if (!fs.existsSync(srcDir)) {
    fs.mkdirSync(srcDir, { recursive: true });
  }

  fs.writeFileSync(VERSION_FILE, content, 'utf8');
  console.log(`✓ Generated version.ts (${version})`);
}

// Run if called directly
if (require.main === module) {
  generateVersionFile();
}

module.exports = { generateVersionFile };

