/**
 * Auto-generated version file
 * Do not edit manually - this file is generated by version-manager.js
 * Updated during build process
 */

export const VERSION = '1.1.3';
export const BUILD_DATE = '2025-11-27T14:13:47.852Z';
export const BUILD_HASH = '4d76b6d';
export const BUILD_BRANCH = 'main';

export interface VersionInfo {
  version: string;
  buildDate: string;
  buildHash: string;
  buildBranch: string;
}

export const VERSION_INFO: VersionInfo = {
  version: VERSION,
  buildDate: BUILD_DATE,
  buildHash: BUILD_HASH,
  buildBranch: BUILD_BRANCH
};

/**
 * Get formatted version string
 */
export function getVersionString(): string {
  return `${VERSION} (${BUILD_BRANCH}@${BUILD_HASH})`;
}

/**
 * Check if current build is a production build
 */
export function isProductionBuild(): boolean {
  return BUILD_BRANCH === 'main' || BUILD_BRANCH === 'master';
}
